### ISSUE TITLE
Change Request

### ISSUE THREAD

**Issue by Nithisha-VK** [SyedAli017/blackjack-game#1]
- [x] Do not apply style on body tag. Always use a classname for applying styles.
- [x] Do not copy the entire code from scrimba. Please try to understand the logic and built with your own variables and functions. So you will not forgot the logic behind it.
- [x] you can loop the string or array like this below to reduce improve the code quality.
  for (let i in cards) {
    cardsEl.textContent += cards[i] + " ";
  }

**Comment by SyedAli017** [comment]
made the changes that you requested
